# Generated by Django 4.2.1 on 2023-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('waist_circumference', models.IntegerField()),
                ('drink', models.IntegerField()),
                ('tobacco', models.IntegerField()),
                ('tobacco_history', models.IntegerField()),
                ('family_diabetes', models.BooleanField()),
                ('gestational', models.BooleanField()),
                ('exercise', models.IntegerField()),
            ],
        ),
    ]
