# Generated by Django 4.2.1 on 2023-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='tobacco_history',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
