# Generated by Django 4.2.1 on 2023-05-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_web', '0002_remove_userinfo_tobacco_history_userinfo_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='family_diabetes',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gestational',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tobacco',
        ),
    ]
